-- MySQL Script generated by MySQL Workbench
-- 09/20/16 09:31:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema icamydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `icamydb` ;

-- -----------------------------------------------------
-- Schema icamydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `icamydb` DEFAULT CHARACTER SET utf8 ;
USE `icamydb` ;

-- -----------------------------------------------------
-- Table `icamydb`.`T_ICM_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icamydb`.`T_ICM_USUARIO` ;

CREATE TABLE IF NOT EXISTS `icamydb`.`T_ICM_USUARIO` (
  `cd_usuario` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ds_tipo` CHAR(1) NOT NULL,
  `nm_usuario` VARCHAR(255) NOT NULL,
  `ds_email` VARCHAR(255) NOT NULL,
  `ds_senha` VARCHAR(255) NOT NULL,
  `nr_cpf` INT(11) NOT NULL,
  `ds_url_foto` VARCHAR(255) NULL,
  PRIMARY KEY (`cd_usuario`),
  UNIQUE INDEX `ds_email_UNIQUE` (`ds_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icamydb`.`T_ICM_PRESTADOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icamydb`.`T_ICM_PRESTADOR` ;

CREATE TABLE IF NOT EXISTS `icamydb`.`T_ICM_PRESTADOR` (
  `cd_usuario_prestador` INT(11) UNSIGNED NOT NULL,
  `nm_fantasia` VARCHAR(255) NULL,
  `ds_razao_social` VARCHAR(255) NULL,
  `nr_cnpj` BIGINT(14) NULL,
  PRIMARY KEY (`cd_usuario_prestador`),
  CONSTRAINT `fk_T_ICM_PRESTADOR_T_ICM_USUARIO`
    FOREIGN KEY (`cd_usuario_prestador`)
    REFERENCES `icamydb`.`T_ICM_USUARIO` (`cd_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icamydb`.`T_ICM_CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icamydb`.`T_ICM_CLIENTE` ;

CREATE TABLE IF NOT EXISTS `icamydb`.`T_ICM_CLIENTE` (
  `cd_usuario_cliente` INT(11) UNSIGNED NOT NULL,
  `qq_coisa` VARCHAR(255) NULL,
  PRIMARY KEY (`cd_usuario_cliente`),
  CONSTRAINT `fk_T_ICM_CLIENTE_T_ICM_USUARIO1`
    FOREIGN KEY (`cd_usuario_cliente`)
    REFERENCES `icamydb`.`T_ICM_USUARIO` (`cd_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icamydb`.`T_ICM_ESTADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icamydb`.`T_ICM_ESTADO` ;

CREATE TABLE IF NOT EXISTS `icamydb`.`T_ICM_ESTADO` (
  `cd_estado` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nm_estado` VARCHAR(255) NOT NULL,
  `ds_sigla` CHAR(2) NOT NULL,
  PRIMARY KEY (`cd_estado`),
  UNIQUE INDEX `nm_estado_UNIQUE` (`nm_estado` ASC),
  UNIQUE INDEX `ds_sigla_UNIQUE` (`ds_sigla` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icamydb`.`T_ICM_CIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icamydb`.`T_ICM_CIDADE` ;

CREATE TABLE IF NOT EXISTS `icamydb`.`T_ICM_CIDADE` (
  `cd_cidade` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cd_estado` INT(11) UNSIGNED NOT NULL,
  `nm_cidade` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cd_cidade`, `cd_estado`),
  INDEX `fk_T_ICM_CIDADE_T_ICM_ESTADO1_idx` (`cd_estado` ASC),
  CONSTRAINT `fk_T_ICM_CIDADE_T_ICM_ESTADO1`
    FOREIGN KEY (`cd_estado`)
    REFERENCES `icamydb`.`T_ICM_ESTADO` (`cd_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icamydb`.`T_ICM_BAIRRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icamydb`.`T_ICM_BAIRRO` ;

CREATE TABLE IF NOT EXISTS `icamydb`.`T_ICM_BAIRRO` (
  `cd_bairro` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cd_cidade` INT(11) UNSIGNED NOT NULL,
  `nm_bairro` VARCHAR(255) NOT NULL,
  `ds_regiao` VARCHAR(255) NULL,
  PRIMARY KEY (`cd_bairro`, `cd_cidade`),
  INDEX `fk_T_ICM_BAIRRO_T_ICM_CIDADE1_idx` (`cd_cidade` ASC),
  CONSTRAINT `fk_T_ICM_BAIRRO_T_ICM_CIDADE1`
    FOREIGN KEY (`cd_cidade`)
    REFERENCES `icamydb`.`T_ICM_CIDADE` (`cd_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icamydb`.`T_ICM_TELEFONE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icamydb`.`T_ICM_TELEFONE` ;

CREATE TABLE IF NOT EXISTS `icamydb`.`T_ICM_TELEFONE` (
  `cd_telefone` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cd_usuario` INT(11) UNSIGNED NOT NULL,
  `ds_tipo` VARCHAR(255) NOT NULL,
  `nr_ddd` INT(3) NOT NULL,
  `nr_telefone` INT(9) NOT NULL,
  `ds_complemento` VARCHAR(255) NULL,
  PRIMARY KEY (`cd_telefone`),
  INDEX `fk_T_ICM_TELEFONE_T_ICM_USUARIO1_idx` (`cd_usuario` ASC),
  CONSTRAINT `fk_T_ICM_TELEFONE_T_ICM_USUARIO1`
    FOREIGN KEY (`cd_usuario`)
    REFERENCES `icamydb`.`T_ICM_USUARIO` (`cd_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icamydb`.`T_ICM_LOGRADOURO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icamydb`.`T_ICM_LOGRADOURO` ;

CREATE TABLE IF NOT EXISTS `icamydb`.`T_ICM_LOGRADOURO` (
  `cd_logradouro` INT(11) UNSIGNED NOT NULL,
  `cd_usuario` INT(11) UNSIGNED NOT NULL,
  `cd_bairro` INT(11) UNSIGNED NOT NULL,
  `ds_logradouro` VARCHAR(255) NOT NULL,
  `nr_logradouro` INT(11) NULL,
  `ds_complemento` VARCHAR(255) NULL,
  `nr_cep` INT(8) NOT NULL,
  PRIMARY KEY (`cd_logradouro`, `cd_bairro`),
  INDEX `fk_T_ICM_LOGRADOURO_T_ICM_BAIRRO1_idx` (`cd_bairro` ASC),
  INDEX `fk_T_ICM_LOGRADOURO_T_ICM_CLIENTE1_idx` (`cd_usuario` ASC),
  CONSTRAINT `fk_T_ICM_LOGRADOURO_T_ICM_BAIRRO1`
    FOREIGN KEY (`cd_bairro`)
    REFERENCES `icamydb`.`T_ICM_BAIRRO` (`cd_bairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_ICM_LOGRADOURO_T_ICM_CLIENTE1`
    FOREIGN KEY (`cd_usuario`)
    REFERENCES `icamydb`.`T_ICM_CLIENTE` (`cd_usuario_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icamydb`.`T_ICM_PRESTADOR_BAIRRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icamydb`.`T_ICM_PRESTADOR_BAIRRO` ;

CREATE TABLE IF NOT EXISTS `icamydb`.`T_ICM_PRESTADOR_BAIRRO` (
  `cd_cidade` INT(11) UNSIGNED NOT NULL,
  `cd_bairro` INT(11) UNSIGNED NOT NULL,
  `cd_usuario` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`cd_cidade`, `cd_bairro`, `cd_usuario`),
  INDEX `fk_T_ICM_PRESTADOR_BAIRRO_T_ICM_PRESTADOR1_idx` (`cd_usuario` ASC),
  CONSTRAINT `fk_T_ICM_PRESTADOR_BAIRRO_T_ICM_BAIRRO1`
    FOREIGN KEY (`cd_bairro` , `cd_cidade`)
    REFERENCES `icamydb`.`T_ICM_BAIRRO` (`cd_bairro` , `cd_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_ICM_PRESTADOR_BAIRRO_T_ICM_PRESTADOR1`
    FOREIGN KEY (`cd_usuario`)
    REFERENCES `icamydb`.`T_ICM_PRESTADOR` (`cd_usuario_prestador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icamydb`.`T_ICM_PORTFOLIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icamydb`.`T_ICM_PORTFOLIO` ;

CREATE TABLE IF NOT EXISTS `icamydb`.`T_ICM_PORTFOLIO` (
  `cd_portfolio` INT(11) UNSIGNED NOT NULL,
  `cd_usuario_prestador` INT(11) UNSIGNED NOT NULL,
  `ds_url` VARCHAR(255) NOT NULL,
  `nm_arquivo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cd_portfolio`, `cd_usuario_prestador`),
  INDEX `fk_T_ICM_PORTFOLIO_T_ICM_PRESTADOR1_idx` (`cd_usuario_prestador` ASC),
  CONSTRAINT `fk_T_ICM_PORTFOLIO_T_ICM_PRESTADOR1`
    FOREIGN KEY (`cd_usuario_prestador`)
    REFERENCES `icamydb`.`T_ICM_PRESTADOR` (`cd_usuario_prestador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icamydb`.`T_ICM_SERVICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icamydb`.`T_ICM_SERVICO` ;

CREATE TABLE IF NOT EXISTS `icamydb`.`T_ICM_SERVICO` (
  `cd_servico` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `st_servico` TINYINT(1) NOT NULL,
  `nm_servico` VARCHAR(255) NOT NULL,
  `ds_servico` VARCHAR(255) NULL,
  PRIMARY KEY (`cd_servico`),
  UNIQUE INDEX `nm_servico_UNIQUE` (`nm_servico` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icamydb`.`T_ICM_OFERTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icamydb`.`T_ICM_OFERTA` ;

CREATE TABLE IF NOT EXISTS `icamydb`.`T_ICM_OFERTA` (
  `cd_oferta` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cd_usuario_prestador` INT(11) UNSIGNED NOT NULL,
  `cd_servico` INT(11) UNSIGNED NOT NULL,
  `vl_oferta` FLOAT(11,2) NOT NULL,
  `ds_prazo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cd_oferta`, `cd_usuario_prestador`, `cd_servico`),
  INDEX `fk_T_ICM_OFERTA_T_ICM_PRESTADOR1_idx` (`cd_usuario_prestador` ASC),
  CONSTRAINT `fk_T_ICM_OFERTA_T_ICM_SERVICO1`
    FOREIGN KEY (`cd_servico`)
    REFERENCES `icamydb`.`T_ICM_SERVICO` (`cd_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_ICM_OFERTA_T_ICM_PRESTADOR1`
    FOREIGN KEY (`cd_usuario_prestador`)
    REFERENCES `icamydb`.`T_ICM_PRESTADOR` (`cd_usuario_prestador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icamydb`.`T_ICM_CONTRATACAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icamydb`.`T_ICM_CONTRATACAO` ;

CREATE TABLE IF NOT EXISTS `icamydb`.`T_ICM_CONTRATACAO` (
  `cd_contratacao` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cd_oferta` INT(11) UNSIGNED NOT NULL,
  `cd_usuario_cliente` INT(11) UNSIGNED NOT NULL,
  `cd_usuario_prestador` INT(11) UNSIGNED NOT NULL,
  `cd_servico` INT(11) UNSIGNED NOT NULL,
  `vl_contratacao` FLOAT(11,2) UNSIGNED NOT NULL,
  `dt_agendada` DATE NULL,
  `hr_agendada` TIME NULL,
  `dt_execucao` DATE NULL,
  `hr_execucao` TIME NULL,
  PRIMARY KEY (`cd_contratacao`, `cd_oferta`, `cd_usuario_cliente`, `cd_usuario_prestador`, `cd_servico`),
  INDEX `fk_T_ICM_CONTRATACAO_T_ICM_OFERTA1_idx` (`cd_oferta` ASC, `cd_usuario_prestador` ASC, `cd_servico` ASC),
  CONSTRAINT `fk_T_ICM_CONTRATACAO_T_ICM_CLIENTE1`
    FOREIGN KEY (`cd_usuario_cliente`)
    REFERENCES `icamydb`.`T_ICM_CLIENTE` (`cd_usuario_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_ICM_CONTRATACAO_T_ICM_OFERTA1`
    FOREIGN KEY (`cd_oferta` , `cd_usuario_prestador` , `cd_servico`)
    REFERENCES `icamydb`.`T_ICM_OFERTA` (`cd_oferta` , `cd_usuario_prestador` , `cd_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icamydb`.`T_ICM_CHAT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icamydb`.`T_ICM_CHAT` ;

CREATE TABLE IF NOT EXISTS `icamydb`.`T_ICM_CHAT` (
  `cd_chat` INT(11) NOT NULL,
  `cd_contratacao` INT(11) UNSIGNED NOT NULL,
  `cd_oferta` INT(11) UNSIGNED NOT NULL,
  `cd_usuario_cliente` INT(11) UNSIGNED NOT NULL,
  `cd_usuario_prestador` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`cd_chat`),
  INDEX `fk_T_ICM_CHAT_T_ICM_CONTRATACAO1_idx` (`cd_contratacao` ASC, `cd_oferta` ASC, `cd_usuario_cliente` ASC, `cd_usuario_prestador` ASC),
  CONSTRAINT `fk_T_ICM_CHAT_T_ICM_CONTRATACAO1`
    FOREIGN KEY (`cd_contratacao` , `cd_oferta` , `cd_usuario_cliente` , `cd_usuario_prestador`)
    REFERENCES `icamydb`.`T_ICM_CONTRATACAO` (`cd_contratacao` , `cd_oferta` , `cd_usuario_cliente` , `cd_usuario_prestador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icamydb`.`T_ICM_MENSAGEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icamydb`.`T_ICM_MENSAGEM` ;

CREATE TABLE IF NOT EXISTS `icamydb`.`T_ICM_MENSAGEM` (
  `cd_mensagem` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cd_chat` INT(11) NOT NULL,
  `cd_usuario` INT(11) UNSIGNED NOT NULL,
  `dt_data_hora` DATETIME NOT NULL,
  `ds_conteudo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cd_mensagem`, `cd_chat`),
  INDEX `fk_T_ICM_MENSAGEM_T_ICM_CHAT1_idx` (`cd_chat` ASC),
  INDEX `fk_T_ICM_MENSAGEM_T_ICM_USUARIO1_idx` (`cd_usuario` ASC),
  CONSTRAINT `fk_T_ICM_MENSAGEM_T_ICM_CHAT1`
    FOREIGN KEY (`cd_chat`)
    REFERENCES `icamydb`.`T_ICM_CHAT` (`cd_chat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_ICM_MENSAGEM_T_ICM_USUARIO1`
    FOREIGN KEY (`cd_usuario`)
    REFERENCES `icamydb`.`T_ICM_USUARIO` (`cd_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icamydb`.`T_ICM_PAGAMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icamydb`.`T_ICM_PAGAMENTO` ;

CREATE TABLE IF NOT EXISTS `icamydb`.`T_ICM_PAGAMENTO` (
  `cd_pagamento` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cd_contratacao` INT(11) UNSIGNED NOT NULL,
  `cd_oferta` INT(11) UNSIGNED NOT NULL,
  `cd_usuario_cliente` INT(11) UNSIGNED NOT NULL,
  `cd_usuario_prestador` INT(11) UNSIGNED NOT NULL,
  `cd_servico` INT(11) UNSIGNED NOT NULL,
  `dt_data_hora` DATETIME NOT NULL,
  `ds_metodo` VARCHAR(255) NOT NULL,
  `st_pagamento` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cd_pagamento`, `cd_contratacao`, `cd_oferta`, `cd_usuario_cliente`, `cd_usuario_prestador`, `cd_servico`),
  INDEX `fk_T_ICM_PAGAMENTO_T_ICM_CONTRATACAO1_idx` (`cd_contratacao` ASC, `cd_oferta` ASC, `cd_usuario_cliente` ASC, `cd_usuario_prestador` ASC, `cd_servico` ASC),
  CONSTRAINT `fk_T_ICM_PAGAMENTO_T_ICM_CONTRATACAO1`
    FOREIGN KEY (`cd_contratacao` , `cd_oferta` , `cd_usuario_cliente` , `cd_usuario_prestador` , `cd_servico`)
    REFERENCES `icamydb`.`T_ICM_CONTRATACAO` (`cd_contratacao` , `cd_oferta` , `cd_usuario_cliente` , `cd_usuario_prestador` , `cd_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icamydb`.`T_ICM_REPASSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icamydb`.`T_ICM_REPASSE` ;

CREATE TABLE IF NOT EXISTS `icamydb`.`T_ICM_REPASSE` (
  `cd_repasse` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cd_pagamento` INT(11) UNSIGNED NOT NULL,
  `cd_contratacao` INT(11) UNSIGNED NOT NULL,
  `cd_usuario_cliente` INT(11) UNSIGNED NOT NULL,
  `cd_usuario_prestador` INT(11) UNSIGNED NOT NULL,
  `cd_oferta` INT(11) UNSIGNED NOT NULL,
  `cd_servico` INT(11) UNSIGNED NOT NULL,
  `dt_repasse` DATETIME NOT NULL,
  `vl_repasse` FLOAT(11,2) NOT NULL,
  `st_repasse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cd_repasse`, `cd_pagamento`, `cd_contratacao`, `cd_usuario_cliente`, `cd_usuario_prestador`, `cd_oferta`, `cd_servico`),
  INDEX `fk_T_ICM_REPASSE_T_ICM_PAGAMENTO1_idx` (`cd_pagamento` ASC, `cd_contratacao` ASC, `cd_oferta` ASC, `cd_usuario_cliente` ASC, `cd_usuario_prestador` ASC, `cd_servico` ASC),
  CONSTRAINT `fk_T_ICM_REPASSE_T_ICM_PAGAMENTO1`
    FOREIGN KEY (`cd_pagamento` , `cd_contratacao` , `cd_oferta` , `cd_usuario_cliente` , `cd_usuario_prestador` , `cd_servico`)
    REFERENCES `icamydb`.`T_ICM_PAGAMENTO` (`cd_pagamento` , `cd_contratacao` , `cd_oferta` , `cd_usuario_cliente` , `cd_usuario_prestador` , `cd_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
